env:
  es2021: true
  node: true
  browser: true
extends:
  - 'airbnb-base'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions: 'off'
  no-prototype-builtins: 'off'
  no-underscore-dangle: 'off'
  no-param-reassign: 'off'
  quotes: ['error', 'single']
ignorePatterns:
  - 'dist/**'
